# Generated by Django 4.0.5 on 2022-06-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('planID', models.AutoField(primary_key=True, serialize=False)),
                ('planName', models.CharField(max_length=100)),
                ('amountOptions', models.CharField(max_length=200)),
                ('tenureOptions', models.CharField(max_length=200)),
                ('benefitPercentage', models.IntegerField(max_length=5)),
                ('benefitType', models.CharField(choices=[('Cashback', 'Cashback'), ('ExtraVoucher', 'Extravoucher'), ('Discount', 'Discount')], default='Cashback', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotionID', models.AutoField(primary_key=True, serialize=False)),
                ('user_cap', models.IntegerField(max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TortoiseAPI.plan')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGoals',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField(max_length=10)),
                ('selectedAmount', models.IntegerField(max_length=10)),
                ('selectedTenure', models.IntegerField(max_length=10)),
                ('depositedAmount', models.IntegerField(max_length=10)),
                ('benefitPercentage', models.IntegerField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TortoiseAPI.plan')),
                ('promotionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TortoiseAPI.promotions')),
            ],
        ),
    ]
