# Generated by Django 4.0.5 on 2022-06-15 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TortoiseAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergoals',
            old_name='planID',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='customergoals',
            name='promotion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='TortoiseAPI.promotions'),
            preserve_default=False,
        ),
    ]
