# Generated by Django 4.0.5 on 2022-06-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TortoiseAPI', '0002_rename_planid_customergoals_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customergoals',
            old_name='plan',
            new_name='planID',
        ),
        migrations.RenameField(
            model_name='customergoals',
            old_name='promotion',
            new_name='promotionID',
        ),
    ]
