# Generated by Django 4.0.5 on 2022-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TortoiseAPI', '0003_rename_plan_customergoals_planid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergoals',
            name='ID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='planID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promotions',
            name='promotionID',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
